language: node_js
node_js: 
  – "14"

branches:
  only:
    - master
    - develop

cache:
  directories: 
    – node_modules

before_install:
  - cat .env.travis | envsubst > .env

install: 
  – npm install

script: 
  – npm run test

before_deploy:
  - zip -r opgg *
  - mkdir -p deploy
  - mv opgg.zip deploy/opgg.zip

deploy:
  - provider : s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: opgg-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
  on:
    branch: master
  - provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: opgg-deploy
  key: opgg.zip
  bundle_type: zip
  application: travis-deploy
  deployment_group: travis-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - hyotaek9812@gmail.com
